### ISSUE TITLE
Hey i want contribute there is Other inference endpoints are missing i will help to implementation 

### ISSUE THREAD

**Issue by huzaifansari54** [shamblett/huggingface_client#8]
Hey i want contribute there is Other inference endpoints are missing i will help to implementation  
Thanks

**Comment by shamblett** [comment]
Ok, no problem, I'll look at any pull requests you generate. As a matter of interest what 'other' inference endpoints are missing?

**Comment by huzaifansari54** [comment]
like text to image , audio To audio etc

**Comment by shamblett** [comment]
OK, what I meant was could you point to the exact API calls that are missing in the API docs [here](https://huggingface.co/docs/api-inference/detailed_parameters) or just raise pull requsts if you prefer.

**Comment by huzaifansari54** [comment]
sure here it is docs  https://huggingface.co/docs/api-inference/tasks/text-to-image 
can i add this  model  and what you think about lang chan support for this pkg ?

**Comment by shamblett** [comment]
This seems to have been added since I did these originally, this is naughty, API's should be versioned to stop this sort of thing happening. Please raise a pull request to add this if you wish.

Not sure what you mean by lang chain support but raise a separate issue for this, leave this issue for API additions.

**Comment by shamblett** [comment]
Work carried out under #11, closing.
